let City = [
    "Agartala",
    "Agatti Island",
    "Agra",
    "Ahmedabad",
    "Aizawl",
    "Akola",
    "Allahabad",
    "Along, Arunachal Pradesh",
    "Amritsar",
    "Assam",
    "Aurangabad, Maharashtra",
    "Bagdogra",
    "Bangalore",
    "Bareli",
    "Belgaum",
    "Bellary",
    "Bhatinda",
    "Bhavnagar",
    "Bhopal",
    "Bhubaneswar",
    "Bhuj, Kutch, Gujarat",
    "Bikaner",
    "Bilaspur, Chhattisgarh",
    "Car Nicobar",
    "Chandigarh",
    "Chennai (Madras)",
    "Coimbatore",
    "Cooch Behar",
    "Cuddapah",
    "Dabolim, Goa",
    "Daman",
    "Daporijo, Arunachal Pradesh",
    "Dehradun, Uttarakhand",
    "Delhi",
    "Dhanbad",
    "Dibrugarh",
    "Dimapur",
    "Diu",
    "Dum Dum",
    "Gandhidham / Kandla",
    "Gaya",
    "Gorakhpur",
    "Guna",
    "Guwahati",
    "Gwalior",
    "Hissar",
    "Hubli",
    "Hyderabad",
    "Begumpet",
    "Imphal",
    "Indore, Madhya Pradesh",
    "Jabalpur, Madhya Pradesh",
    "Jagdalpur",
    "Jaipur / Sanganer",
    "Jaisalmer",
    "Jammu",
    "Jamnagar, Gujurat",
    "Jamshedpur",
    "Jodhpur, Rajasthan",
    "Jorhat",
    "Kailashahar",
    "Kamalpur",
    "Kangra, Himachal Pradesh",
    "Kanpur, Uttar Pradesh",
    "Keshod",
    "Khajuraho",
    "Khowai",
    "Kolhapur",
    "Kota",
    "Kozhikode (Calicut)",
    "Kullu / Bhuntar, Himachal Pradesh",
    "Latur, Maharashtra",
    "Leh",
    "Lucknow",
    "Ludhiana",
    "Madurai",
    "Malda",
    "Mangalore",
    "Mohanbari",
    "Mumbai",
    "Muzaffarnagar",
    "Muzzafarpur",
    "Mysore",
    "Nagpur",
    "Nanded",
    "Nashik",
    "Nedumbassery, Kerala",
    "Neyveli",
    "Osmanabad",
    "Pasighat (Passighat)",
    "Pathankot",
    "Patna",
    "Port Blair",
    "Puducherry",
    "Pune",
    "Raipur",
    "Rajkot",
    "Ramagundam, Andhra Pradesh",
    "Ranchi",
    "Ratnagiri",
    "Rourkela",
    "Rupsi, Meghalaya",
    "Salem",
    "Satna",
    "Shillong",
    "Sholapur (Solapur)",
    "Silchar",
    "Simla, Himachal Pradesh",
    "Srinagar",
    "Surat, Gujarat",
    "Tezpur, Assam",
    "Tezu, Arunachal Pradesh",
    "Tiruchirapalli (Trichy), Tamil Nadu",
    "Tirupati, Andhra Pradesh",
    "Trivandrum, Kerala",
    "Udaipur",
    "Vadodara",
    "Varanasi, Uttar Pradesh",
    "Vijayawada, Andhra Pradesh",
    "Visakhapatnam, Andhra Pradesh",
    "Ziro",
];
let cities = {
    Agartala: "IXA",
    "Agatti Island": "AGX",
    Agra: "AGR",
    Ahmedabad: "AMD",
    Aizawl: "AJL",
    Akola: "AKD",
    Allahabad: "IXD",
    "Along, Arunachal Pradesh": "IXV",
    Amritsar: "ATQ",
    Assam: "IXI",
    "Aurangabad, Maharashtra": "IXU",
    Bagdogra: "IXB",
    Bangalore: "BLR",
    Bareli: "BEK",
    Belgaum: "IXG",
    Bellary: "BEP",
    Bhatinda: "BUP",
    Bhavnagar: "BHU",
    Bhopal: "BHO",
    Bhubaneswar: "BBI",
    "Bhuj, Kutch, Gujarat": "BHJ",
    Bikaner: "BKB",
    "Bilaspur, Chhattisgarh": "PAB",
    "Car Nicobar": "CBD",
    Chandigarh: "IXC",
    "Chennai (Madras)": "MAA",
    Coimbatore: "CJB",
    "Cooch Behar": "COH",
    Cuddapah: "CDP",
    "Dabolim, Goa": "GOI",
    Daman: "NMB",
    "Daporijo, Arunachal Pradesh": "DEP",
    "Dehradun, Uttarakhand": "DED",
    Delhi: "DEL",
    Dhanbad: "DBD",
    Dibrugarh: "DIB",
    Dimapur: "DMU",
    Diu: "DIU",
    "Dum Dum": "CCU",
    "Gandhidham / Kandla": "IXY",
    Gaya: "GAY",
    Gorakhpur: "GOP",
    Guna: "GUX",
    Guwahati: "GAU",
    Gwalior: "GWL",
    Hissar: "HSS",
    Hubli: "HBX",
    Begumpet: "BPM",
    Hyderabad: "HYD",
    Imphal: "IMF",
    "Indore, Madhya Pradesh": "IDR",
    "Jabalpur, Madhya Pradesh": "JLR",
    Jagdalpur: "JGB",
    "Jaipur / Sanganer": "JAI",
    Jaisalmer: "JSA",
    Jammu: "IXJ",
    "Jamnagar, Gujurat": "JGA",
    Jamshedpur: "IXW",
    "Jodhpur, Rajasthan": "JDH",
    Jorhat: "JRH",
    Kailashahar: "IXH",
    Kamalpur: "IXQ",
    "Kangra, Himachal Pradesh": "DHM",
    "Kanpur, Uttar Pradesh": "KNU",
    Keshod: "IXK",
    Khajuraho: "HJR",
    Khowai: "IXN",
    Kolhapur: "KLH",
    Kota: "KTU",
    "Kozhikode (Calicut)": "CCJ",
    "Kullu / Bhuntar, Himachal Pradesh": "KUU",
    "Latur, Maharashtra": "LTU",
    Leh: "IXL",
    Lucknow: "LKO",
    Ludhiana: "LUH",
    Madurai: "IXM",
    Malda: "LDA",
    Mangalore: "IXE",
    Mohanbari: "MOH",
    Mumbai: "BOM",
    Muzaffarnagar: "MZA",
    Muzzafarpur: "MZU",
    Mysore: "MYQ",
    Nagpur: "NAG",
    Nanded: "NDC",
    Nashik: "ISK",
    "Nedumbassery, Kerala": "COK",
    Neyveli: "NVY",
    Osmanabad: "OMN",
    "Pasighat (Passighat)": "IXT",
    Pathankot: "IXP",
    Patna: "PAT",
    "Port Blair": "IXZ",
    Puducherry: "PNY",
    Pune: "PNQ",
    Raipur: "RPR",
    Rajkot: "RAJ",
    "Ramagundam, Andhra Pradesh": "RMD",
    Ranchi: "IXR",
    Ratnagiri: "RTC",
    Rourkela: "RRK",
    "Rupsi, Meghalaya": "RUP",
    Salem: "SXV",
    Satna: "TNI",
    Shillong: "SHL",
    "Sholapur (Solapur)": "SSE",
    Silchar: "IXS",
    "Simla, Himachal Pradesh": "SLV",
    Srinagar: "SXR",
    "Surat, Gujarat": "STV",
    "Tezpur, Assam": "TEZ",
    "Tezu, Arunachal Pradesh": "TEI",
    "Tiruchirapalli (Trichy), Tamil Nadu": "TRZ",
    "Tirupati, Andhra Pradesh": "TIR",
    "Trivandrum, Kerala": "TRV",
    Udaipur: "UDR",
    Vadodara: "BDQ",
    "Varanasi, Uttar Pradesh": "VNS",
    "Vijayawada, Andhra Pradesh": "VGA",
    "Visakhapatnam, Andhra Pradesh": "VTZ",
    Ziro: "ZER",
};
