//---------------------------------------------------------------------Flight details String
let s1 = '<div class="flight_container" ><div class="cont1"><img src="'; //Add image
let s2 =
    '" alt=""' + ' width="65" height="25";' + ' ><br><span class="flightno">'; //Add flightNumber
let s3 = "</span><br><span>"; //Add flight class
let s4 = '</span></div><div class="cont2"><span class="fromcode"> <b>'; //Add fromcode
let s5 = '</b> </span> <br><span class="departure">'; //Add departure
let s6 = '</span><span class="fromdate">'; //Add from date
let s7 = '</span><br><span class="fromcity">'; //Add fromCity
let s8 =
    '</span></div><div class="cont3"><img src="/images/wall-clock.png" alt="" width="24" height="24"><span class="duration"><br>'; //Add duration
let s9 = '</span></div><div class="cont4"><span class="tocode" > <b>'; //Add tocode
let s10 = '</b> </span><br><span class="arrival">'; //Arrival
let s11 = '</span><span class="todate">'; //todate
let s12 = '</span><br><span class="tocity" >'; //toCity
let s13 = '</span></div><div class="buttons"><a href="'; //Add booking next page
let s14 = '"><input type="button" value="Book" class="btn-book"  id="';
let s15 =
    '" onclick="selectFlight(id)"></a><a href="#form"><input type="button" onclick="showForm()" value="&nbsp;Back" class="btn-back"></a></div></div>';

//  s1 + image + s2 + fnumber + s3 + class + s4 + fromcode + s5 + departure + s6 + fromdate + s7
// + fromcity + s8 + duration + s9 + tocode + s10 + arrival + s11 + todate(fromdate + todate) + s12 + tocity + s13 + bookingpage(#) + s14

let flightsArr = [
    {
        departure: "12:00 AM",
        arrival: "2:40 AM",
        duration: "2 hr 40 min",
        airline: "Air India",
        flightno: "AI021",
        Image: "/images/air-india-logo-alt.png",
        todate: 0,
        seatAvailability: 15,
        price: 1250,
    },
    {
        departure: "10:00 AM",
        arrival: "1:10 PM",
        duration: "3 hr 10 min",
        airline: "Air India",
        flightno: "AI023",
        Image: "/images/air-india-logo-alt.png",
        todate: 0,
        seatAvailability: 15,
        price: 3420,
    },
    {
        departure: "7:00 PM",
        arrival: "11:40 PM",
        duration: "4 hr 40 min",
        airline: "Air India",
        flightno: "AI507",
        Image: "/images/air-india-logo-alt.png",
        todate: 0,
        seatAvailability: 15,
        price: 1720,
    },
    {
        departure: "6:00 AM",
        arrival: "8:30 AM",
        duration: "2 hr 30 min",
        airline: "Air India Express",
        flightno: "IX454",
        Image: "/images/air-india-express-logo-alt (1).png",
        todate: 0,
        seatAvailability: 15,
        price: 2450,
    },
    {
        departure: "3:00 PM",
        arrival: "7:00 PM",
        duration: "4 hr 00 min",
        airline: "Air India Express",
        flightno: "IX327",
        Image: "/images/air-india-express-logo-alt (1).png",
        todate: 0,
        seatAvailability: 15,
        price: 6540,
    },
    {
        departure: "5:00 AM",
        arrival: "7:20 AM",
        duration: "2 hr 20 min",
        airline: "AirAsia India",
        flightno: "I5101",
        Image: "/images/airasia-logo-alt.png",
        todate: 0,
        seatAvailability: 15,
        price: 6590,
    },
    {
        departure: "2:00 PM",
        arrival: "5:50 PM",
        duration: "3 hr 50 min",
        airline: "AirAsia India",
        flightno: "I5204",
        Image: "/images/airasia-logo-alt.png",
        todate: 0,
        seatAvailability: 15,
        price: 5470,
    },
    {
        departure: "11:00 PM",
        arrival: "4:20 AM",
        duration: "5 hr 20 min",
        airline: "AirAsia India",
        flightno: "I5106",
        Image: "/images/airasia-logo-alt.png",
        todate: 1,
        seatAvailability: 15,
        price: 5440,
    },
    {
        departure: "8:00 AM",
        arrival: "10:50 AM",
        duration: "2 hr 50 min",
        airline: "Akasa Air	",
        flightno: "QP450",
        Image: "/images/akasa-air-logo-alt.png",
        todate: 0,
        seatAvailability: 15,
        price: 4450,
    },
    {
        departure: "5:00 PM",
        arrival: "9:20 PM",
        duration: "4 hr 20 min",
        airline: "Akasa Air",
        flightno: "QP457",
        Image: "/images/akasa-air-logo-alt.png",
        todate: 0,
        seatAvailability: 15,
        price: 9950,
    },
    {
        departure: "3:00 AM",
        arrival: "5:00 AM",
        duration: "2 hr 00 min",
        airline: "Go First",
        flightno: "G8650",
        Image: "/images/go-first-logo-alt.png",
        todate: 0,
        seatAvailability: 15,
        price: 1050,
    },
    {
        departure: "12:00 PM",
        arrival: "3:30 PM",
        duration: "3 hr 30 min",
        airline: "Go First",
        flightno: "G8609",
        Image: "/images/go-first-logo-alt.png",
        todate: 0,
        seatAvailability: 15,
        price: 2090,
    },
    {
        departure: "9:00 PM",
        arrival: "2:00 AM",
        duration: "5 hr 00 min",
        airline: "Go First",
        flightno: "G8501",
        Image: "/images/go-first-logo-alt.png",
        todate: 1,
        seatAvailability: 15,
        price: 6050,
    },
    {
        departure: "12:00 AM",
        arrival: "1:30 AM",
        duration: "1 hr 30 min",
        airline: "Indigo",
        flightno: "6E701",
        Image: "/images/indigo-logo-alt.png",
        todate: 0,
        seatAvailability: 15,
        price: 1200,
    },
    {
        departure: "9:00 AM",
        arrival: "12:00 PM",
        duration: "3 hr 00 min",
        airline: "Indigo",
        flightno: "6E650",
        Image: "/images/indigo-logo-alt.png",
        todate: 0,
        seatAvailability: 15,
        price: 1350,
    },
    {
        departure: "6:00 PM",
        arrival: "10:30 PM",
        duration: "4 hr 30 min",
        airline: "Indigo	",
        flightno: "6E657",
        Image: "/images/indigo-logo-alt.png",
        todate: 0,
        seatAvailability: 15,
        price: 1450,
    },
    {
        departure: "7:00 AM",
        arrival: "9:40 AM",
        duration: "2 hr 40 min",
        airline: "Jet Airways",
        flightno: "9W450",
        Image: "/images/jet-airways-logo-alt.png",
        todate: 0,
        seatAvailability: 15,
        price: 1570,
    },
    {
        departure: "4:00 PM",
        arrival: "8:10 PM",
        duration: "4 hr 10 min",
        airline: "Jet Airways",
        flightno: "9W054",
        Image: "/images/jet-airways-logo-alt.png",
        todate: 0,
        seatAvailability: 15,
        price: 1680,
    },
    {
        departure: "2:00 AM",
        arrival: "3:50 AM",
        duration: "1 hr 50 min",
        airline: "SpiceJet",
        flightno: "SG107",
        Image: "/images/spicejet-logo-alt.png",
        todate: 0,
        seatAvailability: 15,
        price: 1790,
    },
    {
        departure: "11:00 AM",
        arrival: "2:20 PM",
        duration: "3 hr 20 min",
        airline: "SpiceJet",
        flightno: "SG412",
        Image: "/images/spicejet-logo-alt.png",
        todate: 0,
        seatAvailability: 15,
        price: 1810,
    },
    {
        departure: "8:00 PM",
        arrival: "12:50 AM",
        duration: "4 hr 50 min",
        airline: "SpiceJet",
        flightno: "SG418",
        Image: "/images/spicejet-logo-alt.png",
        todate: 1,
        seatAvailability: 15,
        price: 6510,
    },
    {
        departure: "4:00 AM",
        arrival: "6:10 AM",
        duration: "2 hr 10 min",
        airline: "Vistara",
        flightno: "UK850",
        Image: "/images/vistara-logo-alt.png",
        todate: 0,
        seatAvailability: 15,
        price: 5620,
    },
    {
        departure: "1:00 PM",
        arrival: "4:40 PM",
        duration: "3 hr 40 min",
        airline: "Vistara",
        flightno: "UK205",
        Image: "/images/vistara-logo-alt.png",
        todate: 0,
        seatAvailability: 15,
        price: 4520,
    },
    {
        departure: "10:00 PM",
        arrival: "3:10 AM",
        duration: "5 hr 10 min",
        airline: "Vistara",
        flightno: "UK508",
        Image: "/images/vistara-logo-alt.png",
        todate: 1,
        seatAvailability: 15,
        price: 6580,
    },
];
